name:                catalyst
version:             0.0.0.1
github:              "ChrisPenner/catalyst"
license:             BSD3
author:              "Chris Penner"
maintainer:          "example@example.com"
copyright:           "2021 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:              A Category typeclass hierarchy powerful enough to encode full programs.
# category:            Web

description:         Please see the README on GitHub at <https://github.com/ChrisPenner/catalyst#readme>

dependencies:
- base >= 4.7 && < 5
- profunctors

ghc-options:
  - -Wall

default-extensions:
- TypeOperators
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- LambdaCase
- ViewPatterns
- TypeApplications
- TypeOperators
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- StandaloneDeriving
- TemplateHaskell
- RankNTypes
- GADTs
- PolyKinds

library:
  source-dirs: src
